#!/bin/bash

if [[ "$CI" != 'true' ]]; then
    echo 'Exporting build environment variables...'
    export SDK='iphonesimulator12.0'
    export WORKSPACE='TravisDemo.xcworkspace'
    export DESTINATION='platform=iOS Simulator,OS=12.0,name=iPhone 8'
    export CONFIGURATION='Debug'
fi

rm -rf './build'

# SPCLUB-AdHoc RENA-AdHoc KENSAPO-AdHoc
for scheme in TravisDemo; do
    echo "Compiling....." $scheme
    xcodebuild build \
        -workspace "$WORKSPACE" \
        -scheme $scheme \
        -sdk "$SDK" \
        -destination "$DESTINATION" \
        -derivedDataPath build \
        ONLY_ACTIVE_ARCH=YES \
        -configuration "$CONFIGURATION" | bundle exec xcpretty;

    if test ${PIPESTATUS[0]} -eq 0
    then
        echo "Compiled success" $scheme
    else {
        echo "Compiled fail" $scheme
        exit 1
    }
    fi
done

exit ${PIPESTATUS[0]}
